"""Initial migration.

Revision ID: 2a2fdc101d5e
Revises: 
Create Date: 2024-06-11 15:01:16.690999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2fdc101d5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artigo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.Column('codigoArtigo', sa.String(length=21), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigoArtigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artigo')
    # ### end Alembic commands ###
