"""empty message

Revision ID: 39b9d42b9936
Revises: 9473733ddc93
Create Date: 2024-06-13 21:19:31.479284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b9d42b9936'
down_revision = '9473733ddc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encomenda')
    op.drop_table('linhaEncomenda')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linhaEncomenda',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('encomendaId', sa.INTEGER(), nullable=True),
    sa.Column('artigoId', sa.INTEGER(), nullable=True),
    sa.Column('quantidade', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['encomendaId'], ['encomenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encomenda',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('utilizadorId', sa.INTEGER(), nullable=True),
    sa.Column('aberta', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
